//! C imports for libwayland-client and generated Wayland protocol bindings.
//!
//! This module re-exports the translate-c output generated by build.zig
//! from src/wayland/c.h, which includes wayland-client headers and the
//! generated primary-selection protocol header.

pub const c = @import("c");
